#!/usr/bin/env python

'''
Provide structured data understood by the wiki update.py
'''

class Partner:
    '''defines an entry in the partner table'''
    def __init__(self,image,link):
        self.image = image
        self.link = link

PARTNER_LIST = [
    Partner('supporters_logo_EAMS.png','https://eams-robo.co.jp'),
    Partner('supporters_logo_jDrones.png','http://jdrones.com'),
    Partner('supporters_logo_CubePilot.png','https://www.cubepilot.com/#/home'),
    Partner('supporters_logo_mRobotics.png','https://mrobotics.io'),
    Partner('supporters_logo_Emlid.png','https://emlid.com'),
    Partner('supporters_logo_CUAV.jpg','http://www.cuav.net'),
    Partner('supporters_logo_Craft_and_Theory.png','http://craftandtheoryllc.com'),
    Partner('supporters_logo_LightWare.png','https://lightwarelidar.com'),
    Partner('supporters_logo_SpektreWorks.png','https://spektreworks.com'),
    Partner('supporters_logo_CubePilot.png','https://www.cubepilot.com/#/home'),
    Partner('supporters_logo_Dronebility.png','http://dronebility.com'),
    Partner('supporters_logo_Drone_Japan.jpg','https://drone-j.com'),
    Partner('supporters_logo_RobSense.png','http://robsense.com'),
    Partner('supporters_logo_BlueRobotics.png','https://bluerobotics.com'),
    Partner('supporters_logo_Skyrocket.jpg','https://sky-viper.com'),
    Partner('supporters_logo_Drotek.png','https://drotek.com'),
    Partner('supporters_logo_Harris_Aerial.jpg','https://www.harrisaerial.com'),
    Partner('supporters_logo_AltiGator.jpg','https://altigator.com/en'),
    Partner('supporters_logo_Event_38.png','https://event38.com'),
    Partner('supporters_logo_3DXR.jpg','https://3dxr.co.uk'),
    Partner('supporters_logo_Carbonix.png','https://carbonix.com.au'),
    Partner('supporters_logo_Drones_Center.png','https://drones-center.com'),
    Partner('supporters_logo_Wurzbach_Electronics.png','https://wurzbachelectronics.com'),
    Partner('supporters_logo_TT_Robotix.jpg','http://ttrobotix.com'),
    Partner('supporters_logo_Air_Supply_Aerial.png','https://airsupply.com'),
    Partner('supporters_logo_IR_Lock.jpg','https://irlock.com'),
    Partner('supporters_logo_Benewake.png','http://en.benewake.com'),
    Partner('supporters_logo_Foxtech.jpg','https://foxtechfpv.com'),
    Partner('supporters_logo_BFD_Systems.jpg','https://bfdsystems.com'),
    Partner('supporters_logo_Rubidium_Light.jpg','https://rubidiumlight.com.au/rubidium-rover'),
    Partner('supporters_logo_Makeflyeasy.jpg','http://www.makeflyeasy.com'),
    Partner('supporters_logo_Hexsoon.jpg','http://www.hexsoon.com'),
    Partner('supporters_logo_Micro_Aerial_Projects.png','https://microaerialprojects.com'),
    Partner('supporters_logo_ARACE_UAS.png','https://araceuas.com'),
    Partner('supporters_logo_Qifei.png','https://agrobot.en.alibaba.com'),
    Partner('supporters_logo_Mateksys.png','http://www.mateksys.com'),
    Partner('supporters_logo_Freespace.png','https://freespacesolutions.com.au'),
    Partner('supporters_logo_Holybro.png','http://www.holybro.com'),
    Partner('supporters_logo_ASW.png','https://aerosystemswest.com'),
    Partner('supporters_logo_Bask_Aerospace.jpg','https://baskaerospace.com.au'),
    Partner('supporters_logo_D_Makers.png','https://dmakers.co.kr'),
    Partner('supporters_logo_Hitec.png','https://hitecnology.com'),
    Partner('supporters_logo_AeroScanTech.png','https://aeroscantech.com'),
    Partner('supporters_logo_Quaternium.png','https://quaternium.com'),
    Partner('supporters_logo_NP_UAS_TS.png','http://npuasts.com'),
    Partner('supporters_logo_AION_ROBOTICS.png','https://aionrobotics.com'),
    Partner('supporters_logo_ALTI.jpg','https://altiuas.com'),
    Partner('supporters_logo_Flytrex.png','https://flytrex.com'),
    Partner('supporters_logo_VimDrones.png','https://vimdrones.com'),
    Partner('supporters_logo_UAV_Systems_International.jpg','https://uavsystemsinternational.com'),
    Partner('supporters_logo_UAVEX.png','https://uavex.com'),
    Partner('supporters_logo_Geodrones_Australia.png','https://geodronesaustralia.com.au'),
    Partner('supporters_logo_Dual_RC.png','https://dualrc.com'),
    Partner('supporters_logo_DAVWINGS.png','http://davwings.com'),
    Partner('supporters_logo_FrSky.png','https://frsky-rc.com'),
    Partner('supporters_logo_TaiwanDrone100.png','https://taiwandrone100.com'),
    Partner('supporters_logo_Kraus_Aerospace.png','https://krausaerospace.com'),
    Partner('supporters_logo_Argosdyne.png','http://argosdyne.com/en'),
    Partner('supporters_logo_PDRL.png','https://pdrl.in'),
    Partner('supporters_logo_RadioMaster.png','https://radiomasterrc.com'),
    Partner('supporters_logo_Skydroid.png','http://www.skydroid.xin'),
    Partner('supporters_logo_Asylon.png','https://dronecore.us'),
    Partner('supporters_logo_Watts_Innovation.png','https://wattsinnovations.com'),
    Partner('supporters_logo_Exyn.png','https://exyn.com'),
    Partner('supporters_logo_Telluraves_Aerospace.jpg','https://telluraves.co.za'),
    Partner('supporters_logo_Ardusimple.png','https://www.ardusimple.com'),
    Partner('supporters_logo_qiotek.jpg','https://www.qio-tek.com'),
    Partner('supporters_logo_apd.png','https://powerdrives.net'),
    Partner('supporters_logo_BZB_UAS.png','https://bzbuas.com/'),
    Partner('supporters_logo_Ocius.jpg','https://ocius.com.au/'),
    Partner('supporters_logo_RotorsAndCams.png','https://rotorsandcams.com/'),
    Partner('supporters_logo_blicube.jpg','https://www.blicube.com/'),
    Partner('supporters_logo_ModalAI.png','https://www.modalai.com/'),
    Partner('supporters_ing_logo.png','https://www.ingrobotic.com/'),
    Partner('supporters_logo_SYNEREX.png','http://www.synerex.kr/'),
    Partner('supporters_logo_Offshore_Aviation.png','https://www.Offshoreaviation.com'),
    Partner('supporters_logo_currawong.png','https://www.currawongeng.com/'),
    Partner('supporters_logo_skyways.png','https://skyways.com/'),
    Partner('supporters_logo_Sky-Drones.png','https://sky-drones.com/'),
    Partner('supporters_tata_logo.png','https://www.tataadvancedsystems.com/'),
    Partner('supporters_logo_sparkletech.jpg','https://www.sparkleuav.com/'),
    Partner('supporters_vulcan_logo.jpg','https://vulcanuav.com/'),
    Partner('supporters_fly_dragon_logo.png','https://www.droneassemble.com/'),
    Partner('supporters_horizon31_logo.png','https://www.horizon31.com/'),
    Partner('supporters_skylift_logo.png','http://www.skylift.aero/'),
    Partner('supporters_logo_airvolute.png','https://www.airvolute.com/'),
    Partner('supporters_hylio_logo.png','https://www.hyl.io'),
]