name: Test wiki Linux

on: [push, pull_request]
# paths:
# - "*"
# - "!README.md" <-- don't rebuild on doc change
env: 
  TEST: "1"
jobs:

  build-linux:

    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false  # don't cancel if a job from the matrix fails
      matrix:
        python-version: ["3.8", "3.10"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setting environment
        run: |
          mkdir /tmp/web
          ./Sphinxsetup.sh
      - name: Check image formats
        run: |
          find ./images/ -exec file {} + | grep RIFF -vzq
      - name: Check python3 flake8 formatting
        run : |
          set -eux -o pipefail
          flake8 .
      - name: Test build
        run: |
          export AP_SPHINXOPTS=-W
          ./update.py --parallel 4 --verbose --destdir=/tmp/web
