name: Test wiki Linux

on: [push, pull_request]
# paths:
# - "*"
# - "!README.md" <-- don't rebuild on doc change
env: 
  TEST: "1"
jobs:

  build-linux:

    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false  # don't cancel if a job from the matrix fails
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setting environment
        run: |
          mkdir /tmp/web
          ./Sphinxsetup.sh
      - name: Check image formats
        run: |
          find ./images/ -exec file {} + | grep RIFF -vzq
      - name: Check for extra characters after ref directives
        shell: bash {0}
        run: |
          grep --include=\*.rst -Rn -E '(:ref:`.*?`[_]{0,2}) ([\.,:])' .
          test $? -eq 1
      - name: Check for bad characters before ref directives
        shell: bash {0}
        run: |
          grep --include=\*.rst -Rn -E '[a-zA-Z0-9_:]:ref:' .
          test $? -eq 1
      - name: Check python flake8 formatting
        run : |
          set -eux -o pipefail
          flake8 .
      - name: Test build
        run: |
          ./update.py --parallel 4 --verbose --destdir=/tmp/web
