name: Test wiki Linux

on: [push, pull_request]
# paths:
# - "*"
# - "!README.md" <-- don't rebuild on doc change
env: 
  TEST: "1"
jobs:

  build-linux:

    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false  # don't cancel if a job from the matrix fails
      matrix:
        python-version: ["3.8", "3.10"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setting environment
        run: |
          mkdir /tmp/web
          ./Sphinxsetup.sh
      - name: Check image formats
        run: |
          for i in $(find ./images/); do
              BAD=false
              if file "$i" | grep RIFF; then
                  echo "$i contains RIFF metadata; process file to remove"
                  BAD=true
              fi
              if $BAD; then
                  echo "Bad images found"
                  exit 1
              fi
          done
      - name: Check python3 flake8 formatting
        run : |
          set -eux -o pipefail
          flake8 .
      - name: Test build
        run: |
          export AP_SPHINXOPTS=-W
          ./update.py --parallel 4 --verbose --destdir=/tmp/web
